import type { Metadata } from 'next';
import './globals.css';
import TanstackProvider from '@/providers/tanstack.provider';
import AuthProvider from '@/providers/auth.provider';

export const metadata: Metadata = {
  title: 'IntelliB',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest"></link>
      </head>
      <body className="bg-secondary">
        <AuthProvider>
          <TanstackProvider>{children}</TanstackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
